sonar.projectKey=maxi-tools_maxi-reviewer
sonar.projectName=maxi-reviewer
sonar.organization=maxi-tools

sonar.sources=src
sonar.tests=tests

sonar.test.inclusions=tests/**/*.ts
sonar.coverage.exclusions=src/types.ts,dist/**
sonar.cpd.exclusions=tests/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
